---
title: "08-Prediction"
author: "Yao Yu"
date: "10/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Loading in libraries

library(tidyverse)
library(scales)
library(jtools)
library(kableExtra)
library(statebins)
library(caret)
library(huxtable)

# Reading in Data
past_elections <- read_csv("../data/08-prediction/popvote_1948-2016_clean.csv")
past_elections_state <- read_csv("../data/08-prediction/popvote_bystate_1948-2016_clean.csv")
polls_2020 <- read_csv("../data/08-prediction/president_polls_clean.csv")
polls_2020_state <- read_csv("../data/08-prediction/president_polls_state_clean.csv")
polls_past <- read_csv("../data/08-prediction/pollavg_1968-2016_clean.csv")
polls_past_state <- read_csv("../data/08-prediction/pollavg_bystate_1968-2016_clean.csv")
job_approval_gallup <- read_csv("../data/08-prediction/approval_gallup_1941-2020_clean.csv")
ec <- read_csv("../data/08-prediction/ec_2020.csv")
vep <- read_csv("../data/08-prediction/raw-data/vep_1980-2016.csv")
```

```{r popular vote}

# Setting seed for replicability

set.seed(1347)

# Joining data for model 1968-2016

full_data <- polls_past %>% 
  inner_join(past_elections, by = c("year", "party")) %>% 
  inner_join(job_approval_gallup, by = "year")

# Training models
# 1) pv2p ~ average_poll + party
# 2) pv2p ~ average_poll + last_pv2p + party
# 3) pv2p ~ average_poll + last_pv2p + job_approval + party
# 4) pv2p ~ average_poll + last_pv2p + incumbent_party*job_approval + party
# 5) pv2p ~ average_poll + incumbent_party*job_approval


model_1 <- train(pv2p ~ average_poll + party, 
                 data = full_data, method = "lm", trControl = trainControl(method = "LOOCV"))

model_2 <- train(pv2p ~ average_poll + last_pv2p + party, 
                 data = full_data, method = "lm", trControl = trainControl(method = "LOOCV"))

model_3 <- train(pv2p ~ average_poll + last_pv2p + job_approval + party, 
                 data = full_data, method = "lm", trControl = trainControl(method = "LOOCV"))

model_4 <- train(pv2p ~ average_poll + last_pv2p + incumbent_party*job_approval + party, 
                 data = full_data, method = "lm", trControl = trainControl(method = "LOOCV"))

model_5 <- train(pv2p ~ average_poll + incumbent_party*job_approval, 
                 data = full_data, method = "lm", trControl = trainControl(method = "LOOCV"))

# Table of loocv results

models <- tibble(model = c("Model 1", "Model 2", "Model 3", "Model 4", "Model 5"))

loocv_results <- rbind(model_1$results, model_2$results, model_3$results, model_4$results, model_5$results)

loocv_results_table <- models %>% 
  cbind(loocv_results) %>% 
  tibble()

# Table Presentation of models

model_outputs <- export_summs(model_1$finalModel, model_2$finalModel, model_3$finalModel, 
                              model_4$finalModel, model_5$finalModel,
             coefs = c("Intercept" = "(Intercept)",
                       "Average Poll" = "average_poll",
                       "Republican" = "partyrepublican",
                       "Last pv2p" = "last_pv2p",
                       "Average Job Approval" = "job_approval",
                       "Incumbent Party" = "incumbent_partyTRUE",
                       "Incumbent Party:Average Job Approval" = "`incumbent_partyTRUE:job_approval`"),
             statistics = c(N = "nobs",
                            R2 = "r.squared",
                            R2.adj = "adj.r.squared",
                            sigma = "sigma"))

model_outputs

# quick_pdf(model_outputs, file = "national_models_table.pdf")

# Joining data for 2020 prediction

data_2020 <- polls_2020 %>% 
  mutate(last_pv2p = past_elections %>% filter(year == 2016) %>% pull(pv2p),
         incumbent = case_when(
           party == "republican" ~ TRUE,
           party == "democrat" ~ FALSE
         ),
         incumbent_party = incumbent,
         job_approval = job_approval_gallup %>% filter(year == 2020) %>% pull(job_approval))

# Predicting 2020 using model 4

final_model <- lm(pv2p ~ average_poll + last_pv2p + incumbent_party*job_approval + party, data = full_data)

pred_2020 <- predict.lm(object = final_model, newdata = data_2020, se.fit=TRUE, interval="confidence", level=0.95)

# Simulating 10000 draws to get predictive interval

sim_2020 <- tibble(id = as.numeric(1:20000),
                   candidate = rep(c("Biden", "Trump"), 10000),
                   pred_fit = rep(pred_2020$fit[,1], 10000),
                   pred_se = rep(pred_2020$se.fit, 10000)) %>% 
  mutate(pred_prob = map_dbl(.x = pred_fit, .y = pred_se, ~rnorm(n = 1, mean = .x, sd = .y))) %>% 
  mutate(id = case_when(
    id %% 2 == 1 ~ id,
    id %% 2 == 0 ~ id - 1))

# Scaling predictions to 100 points

sims_2020_scaled <- sim_2020 %>% 
  select(-c(pred_fit, pred_se)) %>% 
  group_by(id) %>% 
  pivot_wider(names_from = "candidate", values_from = "pred_prob") %>% 
  ungroup() %>% 
  mutate(total = Biden + Trump,
         Biden = (Biden / total) * 100,
         Trump = (Trump / total) * 100) %>% 
  select(-total) %>% 
  pivot_longer(Biden:Trump, names_to = "candidate", values_to = "pred_prob")

# Scaling averages

biden <- pred_2020$fit[1,1]
trump <- pred_2020$fit[2,1]
total <- biden + trump
biden <- (biden / total) * 100
trump <- (trump / total) * 100

# Plot 10000 draws

sim_2020_plot <- sims_2020_scaled %>% 
  ggplot(aes(x = pred_prob, color = fct_relevel(candidate, "Trump", "Biden"), 
             fill = fct_relevel(candidate, "Trump", "Biden"))) +
  geom_density(alpha = 0.2) +
  annotate(geom = 'text', x = biden, y = 0.15, label = 'Biden') +
  annotate(geom = 'text', x = trump, y = 0.15, label = 'Trump') +
  theme_classic() +
  labs(
    title = "Two-Party Popular Vote Predictive Interval",
    subtitle = "results are from 10,000 simulations of my model",
    x = "Two-Party Popular Vote",
    y = "Density" ) + 
  scale_x_continuous(breaks = seq(44, 56, by = 2), labels = percent_format(accuracy = 1, scale = 1)) +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_color_manual(values=c("#619CFF", "#F8766D"), breaks = c("Biden", "Trump")) +
  scale_fill_manual(values=c("#619CFF", "#F8766D"), breaks = c("Biden", "Trump")) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank(),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

# Saving plot as image (uncomment to save)

# png("2020_pv2p_interval_plot.png", units="in", width=7, height=5, res=300)
# print(sim_2020_plot)
# dev.off()

# Finding the number of times that Trump has a greater two-paty popular vote

trump_wins <- sims_2020_scaled %>% 
  select(id, candidate, pred_prob) %>% 
  pivot_wider(names_from = "candidate", values_from = "pred_prob") %>% 
  mutate(trump_win = Trump > Biden) %>% 
  summarize(trump_wins = sum(trump_win), .groups = "drop")

```

```{r electoral college}


# Setting seed for replicability

set.seed(1347)

# Joining data for model 1988-2016

full_data <- past_elections_state %>% 
  left_join(polls_past_state, by = c("state", "year", "party")) %>% 
  drop_na() %>% 
  left_join(job_approval_gallup, by = "year") %>% 
  left_join(vep, by = c("year", "state")) 

# Removing 2016 data for loocv

full_data_train <- full_data %>% 
  filter(year != 2016)

full_data_test <- full_data %>% 
  filter(year == 2016)

# Training models 
# 1) cbind(votes, VEP-votes) ~ average_poll + party
# 2) cbind(votes, VEP-votes) ~ average_poll + job_approval + party
# 3) cbind(votes, VEP-votes) ~ average_poll + incumbent_party*job_approval + party

models <- full_data_train %>% 
  group_by(state) %>% 
  group_nest() %>% 
  mutate(data = map(data, ~unnest(., cols = c()))) %>% 
  mutate(model_1 = map(data, ~glm(cbind(votes, VEP-votes) ~ average_poll + party, 
                                  data = .x, family = "binomial")),
         model_2 = map(data, ~glm(cbind(votes, VEP-votes) ~ average_poll + job_approval + party, 
                                  data = .x, family = "binomial")),
         model_3 = map(data, ~glm(cbind(votes, VEP-votes) ~ average_poll + incumbent_party*job_approval + party, 
                                  data = .x, family = "binomial"))) %>% 
  select(-data)

# Calculating rmse for each model

model_results <- models %>% 
  mutate(rmse_model_1 = map_dbl(model_1, ~sqrt(mean(.x$residuals^2)))) %>% 
  mutate(rmse_model_2 = map_dbl(model_2, ~sqrt(mean(.x$residuals^2)))) %>% 
  mutate(rmse_model_3 = map_dbl(model_3, ~sqrt(mean(.x$residuals^2)))) %>% 
  select(-c(model_1, model_2, model_3))

# Model 3 appears to be the best with the lowest rmse (same as with popular vote model)

model_3 <- models %>% 
  select(state, model_3)

# So, now we'll test on the 2016 test data

test_predictions <- full_data_test %>% 
  mutate(party_temp = party) %>% 
  group_by(state, party_temp) %>% 
  group_nest() %>% 
  mutate(data = map(data, ~unnest(., cols = c()))) %>% 
  inner_join(model_3, by = "state") %>% 
  mutate(pred = map_dbl(.x = data, .y = model_3, 
                        ~predict(.y, newdata = .x, type = "response")[[1]]),
         vep = map_dbl(data, ~.x$VEP)) %>% 
  select(-c(data, model_3)) %>% 
  group_by(state) %>% 
  pivot_wider(names_from = "party_temp", values_from = "pred") %>% 
  mutate(democrat = democrat * vep,
         republican = republican * vep) %>% 
  select(-vep) %>% 
  mutate(pred_win = ifelse(democrat > republican, "democrat", "republican")) %>% 
  pivot_longer(democrat:republican, names_to = "party", values_to = "pred_votes") %>% 
  mutate(win = party == pred_win)

# Comparing to see how many states our model predicted correctly

test_correct <- past_elections_state %>% 
  filter(year == 2016) %>% 
  select(state, party, votes) %>% 
  pivot_wider(names_from = "party", values_from = "votes") %>% 
  mutate(party_win = ifelse(democrat > republican, "democrat", "republican")) %>% 
  pivot_longer(democrat:republican, names_to = "party", values_to = "votes") %>% 
  mutate(state_winner = party_win == party) %>% 
  inner_join(test_predictions, by = c("state", "party")) %>% 
  mutate(correct = state_winner == win) %>% 
  filter(correct == FALSE)

# The model was incorrect for Florida, Michigan, Nevada, Pennsylvania, and Wisconsin
# But, they were super close elections, so this model still does a fairly good job

# Training the model again with the full data for 2020 prediction

model_final <- full_data %>% 
  group_by(state) %>% 
  group_nest() %>% 
  mutate(data = map(data, ~unnest(., cols = c()))) %>% 
  mutate(model = map(data, ~glm(cbind(votes, VEP-votes) ~ average_poll + incumbent_party*job_approval + party, 
                                  data = .x, family = "binomial"))) %>% 
  select(-data)

# Joining data for 2020 prediction (using 2016 VEP data)

state_data_2020 <- polls_2020_state %>% 
  mutate(year = 2020,
         incumbent_party = ifelse(party == "republican", TRUE, FALSE)) %>% 
  left_join(job_approval_gallup, by = "year") %>% 
  left_join(vep %>% mutate(year = year + 4), by = c("year", "state")) 

# Predicting 2020 data

state_2020_pred_data <- state_data_2020 %>% 
  mutate(party_temp = party) %>% 
  group_by(state, party_temp) %>% 
  group_nest() %>% 
  mutate(data = map(data, ~unnest(., cols = c()))) %>% 
  inner_join(model_final, by = "state") %>% 
  mutate(pred = map(.x = data, .y = model, 
                        ~predict(.y, newdata = .x, type = "response")),
         pred = map(pred, ~unlist(., use.names=FALSE)),
         mean_pred = map_dbl(pred, ~mean(.x)),
         std_pred = map_dbl(pred, ~sd(.x)),
         vep = map_dbl(data, ~.x$VEP)) %>% 
  select(-c(data, model, pred))

# pv2p of 2020 for each state
  
state_2020_pred_pv2p <- state_2020_pred_data %>% 
  select(-std_pred) %>% 
  group_by(state) %>% 
  pivot_wider(names_from = "party_temp", values_from = "mean_pred") %>% 
  mutate(democrat = democrat * vep,
         republican = republican * vep) %>% 
  select(-vep) %>% 
  mutate(democrat_pv2p = democrat / (democrat + republican) * 100,
         republican_pv2p = republican / (democrat + republican) * 100) %>% 
  select(-c(democrat, republican)) %>% 
  pivot_longer(democrat_pv2p:republican_pv2p, names_to = "party", values_to = "pred_votes") %>% 
  mutate(party = ifelse(party == "democrat_pv2p", "democrat", "republican"))

# Grouping the predictions and calculating winner for each state for the map

state_2020_plot_data <- state_2020_pred_pv2p %>% 
  pivot_wider(names_from = party, values_from = pred_votes) %>% 
  mutate(win_margin = republican - democrat,
         win_margin_group = case_when(
           win_margin >= 5 ~ "Strong Trump",
           win_margin >= 2 ~ "Lean Trump",
           win_margin <= -5 ~ "Strong Biden",
           win_margin <= -2 ~ "Lean Biden",
           TRUE ~ "Toss-Up"
         )) %>% 
  select(state, win_margin, win_margin_group)

pred_2020_scaled_plot <- state_2020_plot_data %>% 
  ggplot(aes(state = state, 
             fill = win_margin_group, 
             name = "Predicted Win Margin")) +
  geom_statebins(border_col = "black", border_size = 1/sqrt(pi)) + 
  theme_statebins() +
  scale_fill_manual(values = c("#619CFF", "#C3D7F7", "#BABABA", "#FACECA", "#F8766D"),
                    breaks = c("Strong Biden", "Lean Biden", "Toss-Up", "Lean Trump", "Strong Trump")) +
  labs(title = "2020 Presidential Election Prediction Map",
       fill = "")

# Saving plot as image (uncomment to save)

# png("2020_electoral_map.png", units="in", width=7, height=5, res=300)
# print(pred_2020_scaled_plot)
# dev.off()

# Creating the electoral college bar

ec_plot_data <- state_2020_plot_data %>% 
  mutate(state = ifelse(state == "District of Columbia", "D.C.", state)) %>% 
  left_join(ec, by = "state") %>% 
  group_by(win_margin_group) %>% 
  summarize(total = sum(electors), .groups = "drop")

# Plot of the ec numbers (bar)

ec_plot <- ec_plot_data %>% 
  ggplot(aes(x = "2020", y = total, fill = fct_relevel(win_margin_group, "Strong Trump", "Lean Trump", "Toss-Up", "Lean Biden", "Strong Biden"), label = total)) +
  geom_col(show.legend = FALSE, width = 0.25) + 
  geom_text(position = position_stack(vjust = 0.5)) +
  geom_hline(yintercept = 270) +
  annotate(geom = 'text', x = 0.7, y = 300, label = '270') +
  coord_flip() + 
  theme_void() + 
  labs(fill = "") +
  scale_fill_manual(values = c("#619CFF", "#C3D7F7", "#BABABA", "#FACECA", "#F8766D"),
                    breaks = c("Strong Biden", "Lean Biden", "Toss-Up", "Lean Trump", "Strong Trump"))

# Saving plot as image

# png("2020_electoral_map_bar.png", units="in", width=6, height=1.5, res=100)
# print(ec_plot)
# dev.off()

# Running 10,000 simulations

state_simulation_data_big <- tibble(key = rep(seq(1, 1000), 102)) %>% 
  arrange(key) %>% 
  mutate(state = rep(state_2020_pred_data$state, 1000),
         party = rep(state_2020_pred_data$party_temp, 1000),
         mean_pred = rep(state_2020_pred_data$mean_pred, 1000),
         std_pred = rep(state_2020_pred_data$std_pred, 1000),
         vep = as.integer(rep(state_2020_pred_data$vep, 1000))) %>% 
  mutate(pred_sim = map_dbl(.x = mean_pred, .y = std_pred, ~rnorm(1, .x, .y)),
         pred_vote = map_dbl(.x = pred_sim, .y = vep, ~rbinom(n = 1, size = .y, prob = .x))) %>% 
  select(-c(mean_pred, std_pred, vep, pred_sim))

democrat_data <- state_simulation_data_big %>% 
  filter(party == "democrat") %>% 
  rename(democrat = pred_vote)

republican_data <- state_simulation_data_big %>% 
  filter(party == "republican") %>% 
  rename(republican = pred_vote)

sim_final_data <- democrat_data %>% 
  inner_join(republican_data, by = c("key", "state")) %>% 
  mutate(state = ifelse(state == "District of Columbia", "D.C.", state)) %>% 
  inner_join(ec %>% select(-year), by = "state") %>% 
  mutate(biden_win = ifelse(democrat > republican, electors, 0)) %>% 
  mutate(trump_win = ifelse(democrat < republican, electors, 0)) %>% 
  select(key, state, biden_win, trump_win) %>% 
  group_by(key) %>% 
  summarize(Biden = sum(biden_win),
            Trump = sum(trump_win),
            .groups = "drop")
  
# Preparing the data for plotting

sim_plot_data <- sim_final_data %>% 
  pivot_longer(Biden:Trump, names_to = "candidate", values_to = "ec") 

# Plotting the simulated ec votes

sim_plot <- sim_plot_data %>% 
  ggplot(aes(x = ec, color = fct_relevel(candidate, "Trump", "Biden"), 
             fill = fct_relevel(candidate, "Trump", "Biden"))) +
  geom_density(alpha = 0.2) +
  annotate(geom = 'text', x = mean(sim_final_data$Biden), y = 0.005, label = 'Biden') +
  annotate(geom = 'text', x = mean(sim_final_data$Trump), y = 0.005, label = 'Trump') +
  theme_classic() +
  labs(
    title = "Electoral College Vote Predictive Interval",
    subtitle = "results are from 1,000 simulations of my state models",
    x = "Electoral College Vote",
    y = "" ) +
  scale_color_manual(values=c("#619CFF", "#F8766D"), breaks = c("Biden", "Trump")) +
  scale_fill_manual(values=c("#619CFF", "#F8766D"), breaks = c("Biden", "Trump")) +
  scale_x_continuous(breaks = c(150, 200, 250, 300, 350, 400)) +
  theme(legend.position = "none",
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank(),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))

# Saving plot as image (uncomment to save)

# png("2020_electoral_interval_plot.png", units="in", width=7, height=5, res=300)
# print(sim_plot)
# dev.off()

# Seeing how many times Trump won the ec

trump_wins_ec <- sim_final_data %>% 
  mutate(trump_win = Trump > Biden) %>% 
  summarize(total = sum(trump_win))

```

```{r}

# Saving pv2p and state predictions

pv2p_pred <- tibble(party = c("democrat", "republican"),
                    pred_pv2p = c(biden, trump))

# write_csv(pv2p_pred, "../data/09-reflection/pv2p_pred.csv")

# write_csv(state_2020_pred_pv2p, "../data/09-reflection/state_pred.csv")

```

