---
title: "02-Economy"
author: "Yao Yu"
date: "9/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Loading in libraries

library(tidyverse)
library(scales)
library(janitor)
library(plotly)
library(rjson)
library(jtools)
library(htmlwidgets)
library(kableExtra)
library(reactable)

# Reading in data. Choosing the variables I want to use in my model and removing
# NAs in economic data

popvote <- read_csv("../data/01-introduction/popvote_1948-2016.csv") %>% 
  select(year, party, winner, candidate, pv, incumbent, incumbent_party)
popvote_state <- read_csv("../data/01-introduction/popvote_bystate_1948-2016.csv")
economy <- read_csv("../data/02-economy/econ.csv") %>% 
  drop_na() %>% 
  select(year, quarter, GDP_growth_qt, GDP_growth_yr, RDI_growth, unemployment, stock_open)
local <- read_csv("../data/02-economy/local.csv") %>% 
  clean_names()
```

```{r economy model}

# Joining the popular vote data with the economy data. I'm only picking the Q2
# data because we currently do not have Q3 data for 2020

economy_model_data <- popvote %>% 
  filter(incumbent_party == TRUE) %>% 
  inner_join(economy, by = "year") %>% 
  filter(quarter == 2)

economy_2020_q2 <- economy %>% 
  filter(year == 2020,
         quarter == 2) 

# I'm choosing to make independent models for GDP per quarter, RDI, and
# unemployment

gdp_model <- lm(data = economy_model_data, pv ~ GDP_growth_qt)
rdi_model <- lm(data = economy_model_data, pv ~ RDI_growth)
unemployment_model <- lm(data = economy_model_data, pv ~ unemployment)

# Viewing results of the model

summ(gdp_model, confint = TRUE)
summ(rdi_model, confint = TRUE)
summ(unemployment_model, confint = TRUE)

# Predicting 2020 pv using the three models and putting them in a nice table. I
# divide each number by 100 to format them as percentages in the tables/graphs.

pred_2020 <- tibble(predictive_variable = c("GDP", "RDI", "Unemployment"),
                    data_2020 = c(economy_2020_q2$GDP_growth_qt / 100,
                                  economy_2020_q2$RDI_growth / 100,
                                  economy_2020_q2$unemployment / 100),
                    pv = c(predict(gdp_model, economy_2020_q2) / 100, 
                           predict(rdi_model, economy_2020_q2) / 100, 
                           predict(unemployment_model, economy_2020_q2) / 100),
                    lower = c(predict(gdp_model, economy_2020_q2, interval = "prediction")[2] / 100,
                              predict(rdi_model, economy_2020_q2, interval = "prediction")[2] / 100,
                              predict(unemployment_model, economy_2020_q2, interval = "prediction")[2] / 100),
                    upper = c(predict(gdp_model, economy_2020_q2, interval = "prediction")[3] / 100,
                              predict(rdi_model, economy_2020_q2, interval = "prediction")[3] / 100,
                              predict(unemployment_model, economy_2020_q2, interval = "prediction")[3] / 100))

# Table for 2020 Prediction Results

model_2020_table <- reactable(
  pred_2020, 
  columns = list(
    predictive_variable = colDef(name = "Economic Variable"),
    data_2020 = colDef(name = "2020 Data", format = colFormat(percent = TRUE, digits = 2)),
    pv = colDef(name = "Estimated Popular Vote", format = colFormat(percent = TRUE, digits = 2)),
    lower = colDef(name = "2.5% CI", format = colFormat(percent = TRUE, digits = 2)),
    upper = colDef(name = "97.5% CI", format = colFormat(percent = TRUE, digits = 2))),
  defaultColDef = colDef(
    align = "center",
    minWidth = 70,
    headerStyle = list(background = "#f7f7f8")
  ),
  bordered = TRUE,
  highlight = TRUE)

# saveWidget(model_2020_table, "gdp_pv_table.html", selfcontained = FALSE, libdir = "lib")

# Graphing the rdi model, which gave the best results out of the three

gdp_graph <- economy_model_data %>% 
  mutate(pv = round(pv / 100, digits = 2),
         GDP_growth_qt = GDP_growth_qt / 100,
         candidate = paste(candidate, "-", year, sep = " ")) %>% 
  ggplot(aes(x = GDP_growth_qt, y = pv, label = candidate)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  theme_classic() +
  labs(title = "Predicting Popular Vote using Election Year Q2 GDP Growth",
       x = "Election Year Q2 GDP Growth",
       y = "Incumbent Party Popular Vote") +
  scale_x_continuous(labels = percent_format(accuracy = 1)) +
  scale_y_continuous(labels = percent_format(accuracy = 1))

gdp_graph_plotly <- ggplotly(gdp_graph, tooltip = c("label", "pv"))

# saveWidget(gdp_graph_plotly, "gdp_pv_plot.html", selfcontained = FALSE, libdir = "lib")

```


```{r adding incumbency to the mix}

# Joining the popular vote data with the economy data while also adding in the
# incumbent legend labels and filtering for incumbent party. I'm only picking
# the Q2 data because we currently do not have Q3 data for 2020.

economy_model_data <- popvote %>% 
  filter(incumbent_party == TRUE) %>% 
  inner_join(economy, by = "year") %>% 
  filter(quarter == 2) %>% 
  mutate(incumbent_text = case_when(
    incumbent == TRUE ~ "Incumbent",
    TRUE ~ "Non-Incumbent"
  ))

# I'm choosing to make independent models for GDP per quarter, RDI, and
# unemployment while keeping incumbent as a second predictive variable in each
# model

gdp_model <- lm(data = economy_model_data, pv ~ GDP_growth_qt + incumbent)
rdi_model <- lm(data = economy_model_data, pv ~ RDI_growth + incumbent)
unemployment_model <- lm(data = economy_model_data, pv ~ unemployment + incumbent)

# Viewing results of the model

summ(gdp_model, confint = TRUE)
summ(rdi_model, confint = TRUE)
summ(unemployment_model, confint = TRUE)

# Adding in incumbent data for 2020

economy_2020_q2 <- economy_2020_q2 %>% 
  mutate(incumbent = TRUE)

# Predicting 2020 pv using the three models and putting them in a nice table. I
# divide each number by 100 to format them as percentages in the tables/graphs.

pred_2020 <- tibble(predictive_variable = c("GDP", "RDI", "Unemployment"),
                    data_2020 = c(economy_2020_q2$GDP_growth_qt / 100,
                                  economy_2020_q2$RDI_growth / 100,
                                  economy_2020_q2$unemployment / 100),
                    pv = c(predict(gdp_model, economy_2020_q2) / 100, 
                           predict(rdi_model, economy_2020_q2) / 100, 
                           predict(unemployment_model, economy_2020_q2) / 100),
                    lower = c(predict(gdp_model, economy_2020_q2, interval = "prediction")[2] / 100,
                              predict(rdi_model, economy_2020_q2, interval = "prediction")[2] / 100,
                              predict(unemployment_model, economy_2020_q2, interval = "prediction")[2] / 100),
                    upper = c(predict(gdp_model, economy_2020_q2, interval = "prediction")[3] / 100,
                              predict(rdi_model, economy_2020_q2, interval = "prediction")[3] / 100,
                              predict(unemployment_model, economy_2020_q2, interval = "prediction")[3] / 100))

# Table for 2020 Prediction Results

model_2020_table <- reactable(
  pred_2020, 
  columns = list(
    predictive_variable = colDef(name = "Economic Variable"),
    data_2020 = colDef(name = "2020 Data", format = colFormat(percent = TRUE, digits = 2)),
    pv = colDef(name = "Estimated Popular Vote", format = colFormat(percent = TRUE, digits = 2)),
    lower = colDef(name = "2.5% CI", format = colFormat(percent = TRUE, digits = 2)),
    upper = colDef(name = "97.5% CI", format = colFormat(percent = TRUE, digits = 2))),
  defaultColDef = colDef(
    align = "center",
    minWidth = 70,
    headerStyle = list(background = "#f7f7f8")
  ),
  bordered = TRUE,
  highlight = TRUE)

# saveWidget(model_2020_table, "gdp_pv_table.html", selfcontained = FALSE, libdir = "lib")

# Graphing the gdp model, which gave the second best result out of the three

gdp_incumbent_graph <- economy_model_data %>% 
  mutate(pv = round(pv / 100, digits = 2),
         GDP_growth_qt = GDP_growth_qt / 100,
         label = paste(candidate, "-", year, sep = " ")) %>% 
  ggplot(aes(x = GDP_growth_qt, y = pv, color = incumbent_text, label = label)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  theme_classic() +
  labs(title = "Predicting Popular Vote using Election Year Q2 GDP Growth\nfor Incumbents and same party Non-Incumbents",
       x = "Election Year Q2 GDP Growth",
       y = "Incumbent Party Popular Vote",
       color = "") +
  scale_x_continuous(labels = percent_format(accuracy = 1)) +
  scale_y_continuous(labels = percent_format(accuracy = 1))

gdp_incumbent_graph_plotly <- ggplotly(gdp_incumbent_graph, tooltip = c("label", "pv"))

# saveWidget(gdp_incumbent_graph_plotly, "gdp_incumbent_pv_plot.html", selfcontained = FALSE, libdir = "lib")

```


```{r local model}

# Looking to see if the local economy is a better predictor for battleground states

local_model_data <- popvote_state %>% 
  left_join(popvote, by = "year") %>% 
  filter(incumbent == TRUE) %>% 
  left_join(local, by = c("state" = "state_and_area", "year")) %>% 
  filter(month == "05",
         state %in% c("Florida", "Ohio", "Maine", "North Carolina", "Georgia", "Pennsylvania")) %>% 
  mutate(pv2p = case_when(
    party == "republican" ~ R_pv2p,
    party == "democrat" ~ D_pv2p
  ))

# Creating our model

local_model <- lm(data = local_model_data, pv2p ~ state:unemployed_prce)
summ(local_model)

# Predicting for 2020

local_2020 <- local %>% 
  filter(year == 2020,
         state_and_area %in% c("Florida", "Ohio", "Maine", "North Carolina", "Georgia", "Pennsylvania"),
         month == "05") %>% 
  rename(state = state_and_area) %>% 
  select(state, unemployed_prce)

# Predicting 2020 pv using the the model and putting it in a nice table. I
# divide each number by 100 to format them as percentages in the tables/graphs.

pred_2020 <- local_2020 %>% 
  mutate(unemployed_prce = unemployed_prce / 100,
         pv2p = predict(local_model, local_2020) / 100,
         lower = predict(local_model, local_2020, interval = "prediction")[,2] / 100,
         upper = predict(local_model, local_2020, interval = "prediction")[,3] / 100)

# Table for 2020 Prediction Results

local_2020_table <- reactable(
  pred_2020, 
  columns = list(
    state = colDef(name = "State"),
    unemployed_prce = colDef(name = "Unemployed Percent", format = colFormat(percent = TRUE, digits = 2)),
    pv2p = colDef(name = "Estimated Two Party Popular Vote", format = colFormat(percent = TRUE, digits = 2)),
    lower = colDef(name = "2.5% CI", format = colFormat(percent = TRUE, digits = 2)),
    upper = colDef(name = "97.5% CI", format = colFormat(percent = TRUE, digits = 2))),
  defaultColDef = colDef(
    align = "center",
    minWidth = 70,
    headerStyle = list(background = "#f7f7f8")
  ),
  bordered = TRUE,
  highlight = TRUE)

# saveWidget(local_2020_table, "local_table.html", selfcontained = FALSE, libdir = "lib")

```

